version:  '3.2'
services:

  jenkins:
    image: jenkinsci/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
    ports:
      - 8080:8080
    container_name: jenkins


  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    volumes:
      - ./artifactory:/artifactory:rw
    ports:
      - 9090:8081
    container_name: artifactory
 tomcat:
    image: tomcat
    depends_on:
      - jenkins
    volumes:
      - ./jenkins/workspace/java-test-app/target/:/usr/local/tomcat/webapps
    ports:
      - 7777:8080
    container_name: tomcat

